export declare const userRoleEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["CUSTOMER", "CAREGIVER", "ADMIN"]>;
export declare const caregiverServiceEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["ELDERLY_CAREGIVER", "SPECIAL_NEEDS_TRAINER"]>;
export declare const bookingStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["PENDING", "CONFIRMED", "COMPLETED", "CANCELLED", "NO_SHOW"]>;
export declare const verificationStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["PENDING", "VERIFIED", "REJECTED", "EXPIRED"]>;
export declare const membershipPlanEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["BASIC", "PREMIUM", "CORPORATE"]>;
export declare const users: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "users";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "users";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        email: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "email";
            tableName: "users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        password: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "password";
            tableName: "users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        firstName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "first_name";
            tableName: "users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        lastName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "last_name";
            tableName: "users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        phone: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "phone";
            tableName: "users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        avatar: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "avatar";
            tableName: "users";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        role: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "role";
            tableName: "users";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "CUSTOMER" | "CAREGIVER" | "ADMIN";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["CUSTOMER", "CAREGIVER", "ADMIN"];
            baseColumn: never;
        }, {}, {}>;
        isActive: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "users";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "users";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "users";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const customers: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "customers";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "customers";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "customers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        address: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "address";
            tableName: "customers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        city: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "city";
            tableName: "customers";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        state: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "state";
            tableName: "customers";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        zipCode: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "zip_code";
            tableName: "customers";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        preferences: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "preferences";
            tableName: "customers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "customers";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const caregivers: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "caregivers";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "caregivers";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "caregivers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        bio: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "bio";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        services: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "services";
            tableName: "caregivers";
            dataType: "array";
            columnType: "PgArray";
            data: ("ELDERLY_CAREGIVER" | "SPECIAL_NEEDS_TRAINER")[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            enumValues: ["ELDERLY_CAREGIVER", "SPECIAL_NEEDS_TRAINER"];
            baseColumn: import("node_modules/drizzle-orm").Column<{
                name: "services";
                tableName: "caregivers";
                dataType: "string";
                columnType: "PgEnumColumn";
                data: "ELDERLY_CAREGIVER" | "SPECIAL_NEEDS_TRAINER";
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: ["ELDERLY_CAREGIVER", "SPECIAL_NEEDS_TRAINER"];
                baseColumn: never;
            }, object, object>;
        }, {}, {}>;
        experience: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "experience";
            tableName: "caregivers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        hourlyRate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "hourly_rate";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        certifications: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "certifications";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        backgroundCheckStatus: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "background_check_status";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "PENDING" | "VERIFIED" | "REJECTED" | "EXPIRED";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["PENDING", "VERIFIED", "REJECTED", "EXPIRED"];
            baseColumn: never;
        }, {}, {}>;
        backgroundCheckDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "background_check_date";
            tableName: "caregivers";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        skillVerification: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "skill_verification";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "PENDING" | "VERIFIED" | "REJECTED" | "EXPIRED";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["PENDING", "VERIFIED", "REJECTED", "EXPIRED"];
            baseColumn: never;
        }, {}, {}>;
        safetyScore: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "safety_score";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        overallRating: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "overall_rating";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        reviewCount: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "review_count";
            tableName: "caregivers";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        isAvailable: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_available";
            tableName: "caregivers";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        languagesSpoken: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "languages_spoken";
            tableName: "caregivers";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("node_modules/drizzle-orm").Column<{
                name: "languages_spoken";
                tableName: "caregivers";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, object, object>;
        }, {}, {}>;
        careTrustScore: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "care_trust_score";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        city: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "city";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        district: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "district";
            tableName: "caregivers";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "caregivers";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "caregivers";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const bookings: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "bookings";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "bookings";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        customerId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "customer_id";
            tableName: "bookings";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        caregiverId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "caregiver_id";
            tableName: "bookings";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        serviceType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "service_type";
            tableName: "bookings";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "ELDERLY_CAREGIVER" | "SPECIAL_NEEDS_TRAINER";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["ELDERLY_CAREGIVER", "SPECIAL_NEEDS_TRAINER"];
            baseColumn: never;
        }, {}, {}>;
        startDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "start_date";
            tableName: "bookings";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        endDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "end_date";
            tableName: "bookings";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "bookings";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "PENDING" | "CONFIRMED" | "COMPLETED" | "CANCELLED" | "NO_SHOW";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["PENDING", "CONFIRMED", "COMPLETED", "CANCELLED", "NO_SHOW"];
            baseColumn: never;
        }, {}, {}>;
        notes: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "notes";
            tableName: "bookings";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isEmergency: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_emergency";
            tableName: "bookings";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        checkIn: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "check_in";
            tableName: "bookings";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        checkOut: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "check_out";
            tableName: "bookings";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        totalPrice: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "total_price";
            tableName: "bookings";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "bookings";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "bookings";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const reviews: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "reviews";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "reviews";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        bookingId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "booking_id";
            tableName: "reviews";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        customerId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "customer_id";
            tableName: "reviews";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        caregiverId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "caregiver_id";
            tableName: "reviews";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        rating: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "rating";
            tableName: "reviews";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        comment: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "comment";
            tableName: "reviews";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "reviews";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const subscriptions: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "subscriptions";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "subscriptions";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        customerId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "customer_id";
            tableName: "subscriptions";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        caregiverId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "caregiver_id";
            tableName: "subscriptions";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        serviceType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "service_type";
            tableName: "subscriptions";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "ELDERLY_CAREGIVER" | "SPECIAL_NEEDS_TRAINER";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["ELDERLY_CAREGIVER", "SPECIAL_NEEDS_TRAINER"];
            baseColumn: never;
        }, {}, {}>;
        frequency: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "frequency";
            tableName: "subscriptions";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        price: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "price";
            tableName: "subscriptions";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        isActive: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "subscriptions";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        startDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "start_date";
            tableName: "subscriptions";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        endDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "end_date";
            tableName: "subscriptions";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "subscriptions";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const memberships: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "memberships";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "memberships";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        customerId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "customer_id";
            tableName: "memberships";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        planType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "plan_type";
            tableName: "memberships";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "BASIC" | "PREMIUM" | "CORPORATE";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["BASIC", "PREMIUM", "CORPORATE"];
            baseColumn: never;
        }, {}, {}>;
        price: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "price";
            tableName: "memberships";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        isActive: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "memberships";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        startDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "start_date";
            tableName: "memberships";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        endDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "end_date";
            tableName: "memberships";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "memberships";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const careReports: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "care_reports";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "care_reports";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        bookingId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "booking_id";
            tableName: "care_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        caregiverId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "caregiver_id";
            tableName: "care_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        customerId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "customer_id";
            tableName: "care_reports";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        progressNotes: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "progress_notes";
            tableName: "care_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        metrics: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "metrics";
            tableName: "care_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        photoUrls: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "photo_urls";
            tableName: "care_reports";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("node_modules/drizzle-orm").Column<{
                name: "photo_urls";
                tableName: "care_reports";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
            }, object, object>;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "care_reports";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const usersRelations: import("node_modules/drizzle-orm").Relations<"users", {
    customer: import("node_modules/drizzle-orm").One<"customers", true>;
    caregiver: import("node_modules/drizzle-orm").One<"caregivers", true>;
}>;
export declare const customersRelations: import("node_modules/drizzle-orm").Relations<"customers", {
    user: import("node_modules/drizzle-orm").One<"users", true>;
    bookings: import("node_modules/drizzle-orm").Many<"bookings">;
    subscriptions: import("node_modules/drizzle-orm").Many<"subscriptions">;
    reviews: import("node_modules/drizzle-orm").Many<"reviews">;
    memberships: import("node_modules/drizzle-orm").Many<"memberships">;
    careReports: import("node_modules/drizzle-orm").Many<"care_reports">;
}>;
export declare const caregiversRelations: import("node_modules/drizzle-orm").Relations<"caregivers", {
    user: import("node_modules/drizzle-orm").One<"users", true>;
    bookings: import("node_modules/drizzle-orm").Many<"bookings">;
    subscriptions: import("node_modules/drizzle-orm").Many<"subscriptions">;
    reviews: import("node_modules/drizzle-orm").Many<"reviews">;
    careReports: import("node_modules/drizzle-orm").Many<"care_reports">;
}>;
export declare const bookingsRelations: import("node_modules/drizzle-orm").Relations<"bookings", {
    customer: import("node_modules/drizzle-orm").One<"customers", true>;
    caregiver: import("node_modules/drizzle-orm").One<"caregivers", true>;
    reviews: import("node_modules/drizzle-orm").Many<"reviews">;
    careReport: import("node_modules/drizzle-orm").One<"care_reports", true>;
}>;
export declare const reviewsRelations: import("node_modules/drizzle-orm").Relations<"reviews", {
    booking: import("node_modules/drizzle-orm").One<"bookings", true>;
    customer: import("node_modules/drizzle-orm").One<"customers", true>;
    caregiver: import("node_modules/drizzle-orm").One<"caregivers", true>;
}>;
export declare const subscriptionsRelations: import("node_modules/drizzle-orm").Relations<"subscriptions", {
    customer: import("node_modules/drizzle-orm").One<"customers", true>;
    caregiver: import("node_modules/drizzle-orm").One<"caregivers", true>;
}>;
export declare const membershipsRelations: import("node_modules/drizzle-orm").Relations<"memberships", {
    customer: import("node_modules/drizzle-orm").One<"customers", true>;
}>;
export declare const careReportsRelations: import("node_modules/drizzle-orm").Relations<"care_reports", {
    booking: import("node_modules/drizzle-orm").One<"bookings", true>;
    caregiver: import("node_modules/drizzle-orm").One<"caregivers", true>;
    customer: import("node_modules/drizzle-orm").One<"customers", true>;
}>;
//# sourceMappingURL=schema.d.ts.map